packages:
  - sites/*
  - packages/ui/*
  - packages/logic/*
  - packages/utils
allowBuilds:
  esbuild: true
  sharp: true

catalog:
  "@img/sharp-darwin-arm64": ^0.34.5
  "@img/sharp-libvips-darwin-arm64": ^1.2.4
  "@lucide/svelte": ^1.11.0
  "@types/node": ^25
  "@typescript/native-preview": 7.0.0-dev.20260421.2
  "@vitest/browser-playwright": ^4.1.5
  sharp: ^0.34.5
  sv-agentation: ^0.2.6
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.19
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.19

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
